				public void Start();
        public void Stop();
        public void AddOpenGloveDeviceToServer();
        public void RemoveOpenGloveDeviceFromServer();
        public void SaveOpenGloveConfiguration();
        public void ConnectToBluetoothDevice();
        public void DisconnectFromBluetoothDevice();
        public void StartCaptureDataFromServer();
        public void StopCaptureDataFromServer();
        public void AddActuator(int region, int positivePin, int negativePin);
        public void AddActuators(List<int> regions, List<int> positivePins, List<int> negativePins);
        public void RemoveActuator(int region);
        public void RemoveActuators(List<int> regions);
        public void ActivateActuators(List<int> regions, List<string> intensities);
        public void ActivateActuatorsTimeTest(List<int> regions, List<string> intensities);
        public void TurnOnActuators();
        public void TurnOffActuators();
        public void TurnOnFlexors();
        public void TurnOffFlexors();
        public void ResetActuators();
        public void AddFlexor(int region, int pin);
        public void AddFlexors(List<int> regions, List<int> pins);
        public void RemoveFlexor(int region);
        public void RemoveFlexors(List<int> regions);
        public void CalibrateFlexors();
        public void ConfirmCalibration();
        public void SetThreshold(int value);
        public void ResetFlexors();
        public void StartIMU();
        public void SetIMUStatus(bool status);
        public void SetRawData(bool status);
        public void SetIMUChoosingData(int value);
				public void ReadOnlyAccelerometerFromIMU();
        public void ReadOnlyGyroscopeFromIMU();
        public void ReadOnlyMagnetometerFromIMU();
        public void ReadOnlyAttitudeFromIMU();
        public void ReadAllDataFromIMU();
        public void TurnOnIMU();
        public void TurnOffIMU();
        public void SetLoopDelay(int value);
        public void ConnectToWebSocketServer();
        public void DisconnectFromWebSocketServer();
        public void GetOpenGloveArduinoVersionSoftware();
